export const routes = {
  home: "/",
  login: "/login",
  register: "/cadastro",
  privacy: "/privacidade",
  terms: "/termos",
  marketplaceRules: "/regras-marketplace",
  publicLawyers: "/advogados",
  dashboard: "/dashboard",
  clients: "/clientes",
  triage: "/triagem",
  marketplace: "/marketplace",
  processes: "/processos",
  documents: "/documentos",
  agenda: "/agenda",
  finance: "/financeiro",
  reports: "/relatorios",
  settings: "/configuracoes",
};
