
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3333, DB=path.join(__dirname,'data','db.json'), PUB=path.join(__dirname,'public'); const sessions=new Map();
const read=()=>JSON.parse(fs.readFileSync(DB,'utf8')); const write=db=>fs.writeFileSync(DB,JSON.stringify(db,null,2));
const hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex'); const id=p=>`${p}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;
const js=(res,s,d)=>{res.writeHead(s,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(d));};
const body=req=>new Promise(r=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{r(b?JSON.parse(b):{})}catch{r({})}})});
const safe=u=>{if(!u)return null; const {passwordHash,...x}=u; return x};
function user(req){let h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):''; if(!t||!sessions.has(t))return null; return read().users.find(u=>u.id===sessions.get(t));}
function need(req,res){let u=user(req); if(!u){js(res,401,{error:'Faça login.'});return null} return u}
function admin(req,res){let u=need(req,res); if(!u)return null; if(u.role!=='admin'){js(res,403,{error:'Acesso restrito.'});return null} return u}
function audit(db,u,a,e,i,m={}){db.auditLogs.unshift({id:id('log'),userId:u,action:a,entityType:e,entityId:i,meta:m,createdAt:new Date().toISOString()})}
const rules=[['Direito Bancário',['banco','empréstimo','juros','cartão','negativação','serasa','desconto','benefício']],['Concursos Públicos',['concurso','edital','banca','nomeação','classificação','redação','cotas']],['Direito Administrativo',['servidor','estado','município','processo administrativo','portaria']],['Direito do Consumidor',['produto','serviço','loja','empresa','garantia','defeito']],['Direito de Família',['divórcio','pensão','guarda','alimentos','filho']],['Inventário e Sucessões',['inventário','herança','falecido','espólio','herdeiro']],['Direito do Trabalho',['demissão','fgts','rescisão','salário','emprego']],['Direito Previdenciário',['inss','aposentadoria','benefício','auxílio','perícia']],['Direito Penal',['crime','prisão','delegacia','boletim','ameaça']],['Direito de Trânsito',['multa','detran','autuação','cnh']],['Direito à Saúde',['plano de saúde','medicamento','cirurgia','tratamento','hospital']],['Direito Imobiliário',['imóvel','aluguel','despejo','condomínio']],['Direito Militar',['militar','pmba','policial militar','periculosidade']]];
const docs={'Direito Bancário':['Contrato bancário','Extratos','Comprovantes de desconto','Prints de cobrança'],'Concursos Públicos':['Edital','Resultado/classificação','Recurso administrativo','Comprovante de inscrição'],'Direito Administrativo':['Processo administrativo','Portarias/atos oficiais','Requerimentos','Contracheques'],'Direito do Consumidor':['Nota fiscal','Contrato','Protocolos','Comprovantes'],'Direito de Família':['Certidões','Comprovantes de renda','Comprovantes de despesas'],'Inventário e Sucessões':['Certidão de óbito','Documentos dos herdeiros','Documentos dos bens'],'Direito do Trabalho':['CTPS','Contracheques','TRCT','Comprovantes'],'Direito Previdenciário':['CNIS','Carta de indeferimento','Laudos médicos'],'Direito Penal':['Boletim de ocorrência','Intimações','Provas'],'Direito de Trânsito':['Notificação','CNH','CRLV','Fotos/prints'],'Direito à Saúde':['Relatório médico','Negativa do plano','Receitas','Exames'],'Direito Imobiliário':['Contrato','Matrícula','Comprovantes','Notificações'],'Direito Militar':['Identidade funcional','Contracheques','Atos administrativos'],'Outros':['Documentos pessoais','Comprovantes','Conversas','Notificações']};
const qs={'Direito Bancário':['Qual banco está envolvido?','Existe contrato?','Houve negativação?'],'Concursos Públicos':['Qual concurso e banca?','Qual fase?','Houve recurso administrativo?'],'Direito Administrativo':['Qual órgão está envolvido?','Há processo administrativo?','Existe prazo?'],'Direito do Consumidor':['Qual empresa?','Quando ocorreu?','Houve protocolo?'],'Direito de Família':['Há filhos menores?','Existe acordo?','Há urgência?'],'Inventário e Sucessões':['Quando ocorreu o falecimento?','Há bens?','Todos concordam?'],'Direito do Trabalho':['Qual período trabalhado?','Havia carteira assinada?','Recebeu rescisão?'],'Direito Previdenciário':['Qual benefício?','Houve indeferimento?','Possui laudos?'],'Direito Penal':['Há intimação?','Quando ocorreu?','Existe BO?'],'Direito de Trânsito':['Qual infração?','Quando recebeu?','Há prazo?'],'Direito à Saúde':['Qual tratamento foi negado?','Há relatório médico?','Existe urgência?'],'Direito Imobiliário':['Compra, venda, aluguel ou posse?','Existe contrato?','Há notificação?'],'Direito Militar':['Qual corporação?','Há ato administrativo?','Existe prazo?'],'Outros':['Quem está envolvido?','Quando ocorreu?','Quais documentos possui?']};
function area(desc){let t=String(desc).toLowerCase(),best=['Outros',0]; for(const [a,ks] of rules){let s=ks.filter(k=>t.includes(k)).length; if(s>best[1])best=[a,s]} return best[0]}
function mat(desc,a,dt=''){let s=0,t=String(desc),all=t+' '+dt; if(t.length>=60)s+=20;if(t.length>=180)s+=15;if(/\d{1,2}\/\d{1,2}|\d{4}|ontem|hoje|prazo/i.test(t))s+=15;if(/contrato|documento|comprovante|print|edital|notificação|extrato|laudo|prova/i.test(all))s+=20;if(a!='Outros')s+=10;if(/quero|preciso|resolver|indenização|defesa/i.test(t.toLowerCase()))s+=10;return Math.min(s,100)}
function urg(desc){let t=String(desc).toLowerCase(); if(/prisão|risco de vida|cirurgia urgente|despejo iminente/.test(t))return 'crítica'; if(/prazo|audiência|intimação|notificação|recurso|corte|negativação|liminar/.test(t))return 'alta'; if(/urgente|rápido|prejuízo|dano/.test(t))return 'média'; return 'baixa'}
function diag(desc,dt=''){let a=area(desc),m=mat(desc,a,dt),u=urg(desc); let risks=[]; if(u==='alta'||u==='crítica')risks.push('Há possível urgência ou prazo. Recomenda-se análise rápida.'); else risks.push('Nenhum alerta crítico automático identificado.'); return {legalArea:a,maturityScore:m,urgencyLevel:u,summary:`A narrativa indica possível demanda relacionada a ${a}. A análise é preliminar e depende da conferência dos documentos.`,followUpQuestions:qs[a]||qs.Outros,suggestedDocuments:docs[a]||docs.Outros,riskAlerts:risks,preliminaryTheses:[`Possível medida jurídica relacionada a ${a}, a depender da análise documental.`],nextSteps:['Confirmar dados do cliente.','Solicitar documentos essenciais.','Verificar urgência e prazo.','Submeter à análise individual por advogado.'],warning:'As informações apresentadas possuem caráter preliminar e informativo, não substituindo a análise individual por advogado habilitado.'}}
async function api(req,res){let url=new URL(req.url,`http://${req.headers.host}`),db=read(),m=req.method;
 if(m==='GET'&&url.pathname==='/api/health')return js(res,200,{ok:true,app:'ConectaJus'});
 if(m==='POST'&&url.pathname==='/api/auth/register'){let b=await body(req); if(!b.name||!b.email||!b.password)return js(res,400,{error:'Nome, e-mail e senha são obrigatórios.'}); if(!b.termsAccepted)return js(res,400,{error:'Aceite os termos.'}); if(db.users.some(u=>u.email===b.email))return js(res,409,{error:'E-mail já cadastrado.'}); let u={id:id('user'),name:b.name,email:b.email,phone:b.phone||'',passwordHash:hash(b.password),role:'client',city:b.city||'',state:b.state||'',createdAt:new Date().toISOString()}; db.users.push(u); audit(db,u.id,'USER_REGISTERED','User',u.id); write(db); let tk=id('session'); sessions.set(tk,u.id); return js(res,201,{token:tk,user:safe(u)})}
 if(m==='POST'&&url.pathname==='/api/auth/login'){let b=await body(req),u=db.users.find(x=>x.email===b.email&&x.passwordHash===hash(b.password)); if(!u)return js(res,401,{error:'Credenciais inválidas.'}); let tk=id('session'); sessions.set(tk,u.id); audit(db,u.id,'USER_LOGIN','User',u.id); write(db); return js(res,200,{token:tk,user:safe(u)})}
 if(m==='POST'&&url.pathname==='/api/ai/diagnosis'){let b=await body(req); if(!b.description||b.description.length<20)return js(res,400,{error:'Descreva melhor o caso.'}); return js(res,200,{diagnosis:diag(b.description,b.documentsText||'')})}
 if(m==='POST'&&url.pathname==='/api/cases'){let u=need(req,res); if(!u)return; let b=await body(req); if(!b.description||b.description.length<20)return js(res,400,{error:'Descrição insuficiente.'}); let d=diag(b.description,b.documentsText||''), c={id:id('case'),userId:u.id,internalNumber:`CJ-${new Date().getFullYear()}-${String(db.cases.length+1).padStart(6,'0')}`,legalArea:b.legalArea||d.legalArea,subject:b.subject||d.legalArea,description:b.description,city:b.city||u.city||'',state:b.state||u.state||'',urgencyLevel:d.urgencyLevel,maturityScore:d.maturityScore,status:'new',aiSummary:d.summary,aiDiagnosis:d,nextSteps:d.nextSteps,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; db.cases.unshift(c); audit(db,u.id,'CASE_CREATED','LegalCase',c.id); write(db); return js(res,201,{case:c})}
 if(m==='GET'&&url.pathname==='/api/cases'){let u=need(req,res); if(!u)return; return js(res,200,{cases:u.role==='admin'?db.cases:db.cases.filter(c=>c.userId===u.id)})}
 let cm=url.pathname.match(/^\/api\/cases\/([^\/]+)$/); if(m==='GET'&&cm){let u=need(req,res); if(!u)return; let c=db.cases.find(x=>x.id===cm[1]); if(!c)return js(res,404,{error:'Caso não encontrado.'}); if(u.role!=='admin'&&c.userId!==u.id)return js(res,403,{error:'Acesso negado.'}); return js(res,200,{case:c,user:safe(db.users.find(x=>x.id===c.userId)),documents:db.documents.filter(d=>d.caseId===c.id),notes:db.notes.filter(n=>n.caseId===c.id)})}
 let dm=url.pathname.match(/^\/api\/cases\/([^\/]+)\/documents$/); if(m==='POST'&&dm){let u=need(req,res); if(!u)return; let b=await body(req),c=db.cases.find(x=>x.id===dm[1]); if(!c)return js(res,404,{error:'Caso não encontrado.'}); let d={id:id('doc'),caseId:c.id,userId:u.id,fileName:b.fileName||'Documento informado',category:b.category||'outros',description:b.description||'',createdAt:new Date().toISOString()}; db.documents.unshift(d); audit(db,u.id,'DOCUMENT_RECORDED','Document',d.id); write(db); return js(res,201,{document:d})}
 if(m==='GET'&&url.pathname==='/api/admin/dashboard'){let a=admin(req,res); if(!a)return; let cs=db.cases,avg=cs.length?Math.round(cs.reduce((s,c)=>s+(c.maturityScore||0),0)/cs.length):0; return js(res,200,{metrics:{totalCases:cs.length,newCases:cs.filter(c=>c.status==='new').length,urgentCases:cs.filter(c=>['alta','crítica'].includes(c.urgencyLevel)).length,converted:cs.filter(c=>c.status==='converted').length,averageMaturity:avg,totalClients:db.users.filter(u=>u.role==='client').length}})}
 if(m==='GET'&&url.pathname==='/api/admin/cases'){let a=admin(req,res); if(!a)return; let cs=[...db.cases],q=Object.fromEntries(url.searchParams.entries()); if(q.search){let s=q.search.toLowerCase(); cs=cs.filter(c=>JSON.stringify(c).toLowerCase().includes(s))} if(q.legalArea)cs=cs.filter(c=>c.legalArea===q.legalArea); if(q.status)cs=cs.filter(c=>c.status===q.status); return js(res,200,{cases:cs.map(c=>({...c,user:safe(db.users.find(u=>u.id===c.userId))}))})}
 let ac=url.pathname.match(/^\/api\/admin\/cases\/([^\/]+)$/); if(m==='GET'&&ac){let a=admin(req,res); if(!a)return; let c=db.cases.find(x=>x.id===ac[1]); if(!c)return js(res,404,{error:'Caso não encontrado.'}); return js(res,200,{case:{...c,user:safe(db.users.find(u=>u.id===c.userId))},notes:db.notes.filter(n=>n.caseId===c.id),documents:db.documents.filter(d=>d.caseId===c.id)})}
 let st=url.pathname.match(/^\/api\/admin\/cases\/([^\/]+)\/status$/); if(m==='PATCH'&&st){let a=admin(req,res); if(!a)return; let b=await body(req),c=db.cases.find(x=>x.id===st[1]); if(!c)return js(res,404,{error:'Caso não encontrado.'}); c.status=b.status||c.status; c.updatedAt=new Date().toISOString(); audit(db,a.id,'CASE_STATUS_UPDATED','LegalCase',c.id,{status:c.status}); write(db); return js(res,200,{case:c})}
 let nt=url.pathname.match(/^\/api\/admin\/cases\/([^\/]+)\/notes$/); if(m==='POST'&&nt){let a=admin(req,res); if(!a)return; let b=await body(req),n={id:id('note'),caseId:nt[1],adminId:a.id,note:b.note||'',createdAt:new Date().toISOString()}; db.notes.unshift(n); audit(db,a.id,'INTERNAL_NOTE_CREATED','Note',n.id); write(db); return js(res,201,{note:n})}
 return js(res,404,{error:'Rota não encontrada.'})}
function serve(req,res){let f=req.url.split('?')[0]; if(f==='/')f='/index.html'; let full=path.normalize(path.join(PUB,f)); if(!full.startsWith(PUB)){res.writeHead(403);return res.end('Forbidden')} fs.readFile(full,(e,d)=>{if(e){fs.readFile(path.join(PUB,'index.html'),(e2,d2)=>{if(e2){res.writeHead(404);res.end('Not found')}else{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(d2)}});return} let ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript; charset=utf-8'}; res.writeHead(200,{'Content-Type':types[ext]||'text/plain'});res.end(d)})}
http.createServer((req,res)=>req.url.startsWith('/api/')?api(req,res):serve(req,res)).listen(PORT,()=>{console.log(`ConectaJus em http://localhost:${PORT}`);console.log('Admin: admin@conectajus.local | senha: 1234')});
